name: Docker
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    name: release docker image
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          file: dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: chigusa/aria2:latest
